/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef HCCL_KFC_SERVER_MESSAGE_H
#define HCCL_KFC_SERVER_MESSAGE_H

#include <cstdint>

namespace HcclKfcProtocol {

constexpr uint32_t KFC_MAX_MISSION_NUM = 2U;
constexpr uint32_t KFC_SIGNAL_REGIONS_PER_MISSION = 2U;
constexpr uint32_t KFC_SIGNAL_REGION_NUM = KFC_MAX_MISSION_NUM * KFC_SIGNAL_REGIONS_PER_MISSION;
constexpr uint32_t KFC_COMMIT_REGION_INDEX = 0U;
constexpr uint32_t KFC_WAIT_REGION_INDEX = 1U;

enum KfcConcurrentAllGatherParamIndex : uint32_t {
    KFC_CONCURRENT_AG_OP_ID = 0,
    KFC_CONCURRENT_AG_MESH_INPUT = 1,
    KFC_CONCURRENT_AG_MESH_OUTPUT = 2,
    KFC_CONCURRENT_AG_MESH_OUTPUT_OFFSET = 3,
    KFC_CONCURRENT_AG_MESH_SLICE_SIZE = 4,
    KFC_CONCURRENT_AG_MESH_GO_SIZE_0 = 5,
    KFC_CONCURRENT_AG_MESH_GO_SIZE_1 = 6,
    KFC_CONCURRENT_AG_MESH_GO_SIZE_2 = 7,
    KFC_CONCURRENT_AG_MESH_GO_SIZE_3 = 8,
    KFC_CONCURRENT_AG_MESH_INPUT_OUTPUT_EQUAL = 9,
    KFC_CONCURRENT_AG_NHR_INPUT = 10,
    KFC_CONCURRENT_AG_NHR_OUTPUT = 11,
    KFC_CONCURRENT_AG_NHR_SLICE_SIZE = 12,
    KFC_CONCURRENT_AG_NHR_SLICE_SIZE_PER_JETTY = 13,
    KFC_CONCURRENT_AG_NHR_LAST_SLICE_SIZE_PER_JETTY = 14,
    KFC_CONCURRENT_AG_NHR_REPEAT_NUM_INV = 15,
    KFC_CONCURRENT_AG_NHR_INPUT_SLICE_STRIDE = 16,
    KFC_CONCURRENT_AG_NHR_OUTPUT_SLICE_STRIDE = 17,
    KFC_CONCURRENT_AG_NHR_INPUT_REPEAT_STRIDE = 18,
    KFC_CONCURRENT_AG_NHR_OUTPUT_REPEAT_STRIDE = 19,
    KFC_CONCURRENT_AG_NHR_INPUT_OUTPUT_EQUAL = 20,
    KFC_CONCURRENT_AG_NHR_GO_SIZE_0 = 21,
    KFC_CONCURRENT_AG_NHR_GO_SIZE_1 = 22,
    KFC_CONCURRENT_AG_NHR_GO_SIZE_2 = 23,
    KFC_CONCURRENT_AG_NHR_GO_SIZE_3 = 24,
    KFC_CONCURRENT_AG_PARAM_NUM = 25,
};

} // namespace HcclKfcProtocol

#endif
