/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef HCCL_KFC_SERVER_MESSAGE_H
#define HCCL_KFC_SERVER_MESSAGE_H

#include <cstdint>

namespace HcclKfcProtocol {

constexpr uint32_t KFC_MAX_MISSION_NUM = 2U;
constexpr uint32_t KFC_SIGNAL_REGIONS_PER_MISSION = 2U;
constexpr uint32_t KFC_SIGNAL_REGION_NUM = KFC_MAX_MISSION_NUM * KFC_SIGNAL_REGIONS_PER_MISSION;
constexpr uint32_t KFC_COMMIT_REGION_INDEX = 0U;
constexpr uint32_t KFC_WAIT_REGION_INDEX = 1U;

enum KfcConcurrentAllGatherParamIndex : uint32_t {
    KFC_CONCURRENT_AG_OP_ID = 0,
    KFC_CONCURRENT_AG_MESH_INPUT = 1,
    KFC_CONCURRENT_AG_MESH_OUTPUT = 2,
    KFC_CONCURRENT_AG_MESH_OUTPUT_OFFSET = 3,
    KFC_CONCURRENT_AG_MESH_SLICE_SIZE = 4,
    KFC_CONCURRENT_AG_MESH_GO_SIZE_0 = 5,
    KFC_CONCURRENT_AG_MESH_GO_SIZE_1 = 6,
    KFC_CONCURRENT_AG_MESH_GO_SIZE_2 = 7,
    KFC_CONCURRENT_AG_MESH_GO_SIZE_3 = 8,
    KFC_CONCURRENT_AG_MESH_CURRENT_RANK_SLICE_INPUT_OFFSET = 9,
    KFC_CONCURRENT_AG_MESH_REPEAT_NUM_INV = 10,
    KFC_CONCURRENT_AG_MESH_INPUT_REPEAT_STRIDE = 11,
    KFC_CONCURRENT_AG_MESH_OUTPUT_REPEAT_STRIDE = 12,
    KFC_CONCURRENT_AG_MESH_LAST_SLICE_SIZE = 13,
    KFC_CONCURRENT_AG_MESH_INPUT_OUTPUT_EQUAL = 14,
    KFC_CONCURRENT_AG_MESH_PARAM_NUM = 15,
    KFC_CONCURRENT_AG_NHR_INPUT = KFC_CONCURRENT_AG_MESH_PARAM_NUM,
    KFC_CONCURRENT_AG_NHR_OUTPUT = 16,
    KFC_CONCURRENT_AG_NHR_SLICE_SIZE = 17,
    KFC_CONCURRENT_AG_NHR_SLICE_SIZE_PER_JETTY = 18,
    KFC_CONCURRENT_AG_NHR_LAST_SLICE_SIZE_PER_JETTY = 19,
    KFC_CONCURRENT_AG_NHR_REPEAT_NUM_INV = 20,
    KFC_CONCURRENT_AG_NHR_INPUT_SLICE_STRIDE = 21,
    KFC_CONCURRENT_AG_NHR_OUTPUT_SLICE_STRIDE = 22,
    KFC_CONCURRENT_AG_NHR_INPUT_REPEAT_STRIDE = 23,
    KFC_CONCURRENT_AG_NHR_OUTPUT_REPEAT_STRIDE = 24,
    KFC_CONCURRENT_AG_NHR_INPUT_OUTPUT_EQUAL = 25,
    KFC_CONCURRENT_AG_NHR_GO_SIZE_0 = 26,
    KFC_CONCURRENT_AG_NHR_GO_SIZE_1 = 27,
    KFC_CONCURRENT_AG_NHR_GO_SIZE_2 = 28,
    KFC_CONCURRENT_AG_NHR_GO_SIZE_3 = 29,
    KFC_CONCURRENT_AG_PARAM_NUM = 30,
};

// Parallel Mesh+NHR AllGather uses the same two persistent KFC missions as the
// concurrent variant, but each mission executes twice.  The payload therefore
// carries invariant addresses/sizes; the server reconstructs the four
// phase-specific TemplateDataParams from these values and its static topology.
enum KfcParallelAllGatherParamIndex : uint32_t {
    KFC_PARALLEL_AG_OP_ID = 0,
    KFC_PARALLEL_AG_INPUT = 1,
    KFC_PARALLEL_AG_OUTPUT = 2,
    KFC_PARALLEL_AG_TOTAL_SIZE = 3,
    KFC_PARALLEL_AG_OUTPUT_STRIDE = 4,
    KFC_PARALLEL_AG_PART0_SIZE = 5,
    KFC_PARALLEL_AG_PART1_SIZE = 6,
    KFC_PARALLEL_AG_PART1_OFFSET = 7,
    KFC_PARALLEL_AG_MESH_PHASE_DONE_ADDR = 8,
    KFC_PARALLEL_AG_NHR_PHASE_DONE_ADDR = 9,
    KFC_PARALLEL_AG_PART0_GO_SIZE_0 = 10,
    KFC_PARALLEL_AG_PART0_GO_SIZE_1 = 11,
    KFC_PARALLEL_AG_PART0_GO_SIZE_2 = 12,
    KFC_PARALLEL_AG_PART0_GO_SIZE_3 = 13,
    KFC_PARALLEL_AG_PART1_GO_SIZE_0 = 14,
    KFC_PARALLEL_AG_PART1_GO_SIZE_1 = 15,
    KFC_PARALLEL_AG_PART1_GO_SIZE_2 = 16,
    KFC_PARALLEL_AG_PART1_GO_SIZE_3 = 17,
    KFC_PARALLEL_AG_PART0_SLICE_PER_JETTY = 18,
    KFC_PARALLEL_AG_PART0_LAST_SLICE_PER_JETTY = 19,
    KFC_PARALLEL_AG_PART1_SLICE_PER_JETTY = 20,
    KFC_PARALLEL_AG_PART1_LAST_SLICE_PER_JETTY = 21,
    KFC_PARALLEL_AG_PARAM_NUM = 22,
    // These two words live in the same 32-XN queue record. They are GM
    // rendezvous flags shared by the Mesh and NHR CCU missions.
    KFC_PARALLEL_AG_MESH_PHASE_DONE_STORAGE = 30,
    KFC_PARALLEL_AG_NHR_PHASE_DONE_STORAGE = 31,
    KFC_PARALLEL_AG_STORAGE_NUM = 32,
};

enum KfcConcurrentAllToAllParamIndex : uint32_t {
    KFC_CONCURRENT_A2A_OP_ID = 0,
    KFC_CONCURRENT_A2A_MESH_INPUT = 1,
    KFC_CONCURRENT_A2A_MESH_OUTPUT = 2,
    KFC_CONCURRENT_A2A_MESH_SLICE_SIZE = 3,
    KFC_CONCURRENT_A2A_MESH_SRC_STRIDE = 4,
    KFC_CONCURRENT_A2A_MESH_SRC_OFFSET = 5,
    KFC_CONCURRENT_A2A_MESH_DST_OFFSET = 6,
    KFC_CONCURRENT_A2A_MESH_GO_SIZE_0 = 7,
    KFC_CONCURRENT_A2A_MESH_GO_SIZE_1 = 8,
    KFC_CONCURRENT_A2A_MESH_GO_SIZE_2 = 9,
    KFC_CONCURRENT_A2A_MESH_GO_SIZE_3 = 10,
    KFC_CONCURRENT_A2A_MESH_SLICE_SIZE_PER_JETTY = 11,
    KFC_CONCURRENT_A2A_MESH_LAST_SLICE_SIZE_PER_JETTY = 12,
    KFC_CONCURRENT_A2A_MESH_PARAM_NUM = 13,
    KFC_CONCURRENT_A2A_CLOS_INPUT = KFC_CONCURRENT_A2A_MESH_PARAM_NUM,
    KFC_CONCURRENT_A2A_CLOS_OUTPUT = 14,
    KFC_CONCURRENT_A2A_CLOS_SLICE_SIZE = 15,
    KFC_CONCURRENT_A2A_CLOS_SRC_STRIDE = 16,
    KFC_CONCURRENT_A2A_CLOS_SRC_OFFSET = 17,
    KFC_CONCURRENT_A2A_CLOS_DST_OFFSET = 18,
    KFC_CONCURRENT_A2A_CLOS_GO_SIZE_0 = 19,
    KFC_CONCURRENT_A2A_CLOS_GO_SIZE_1 = 20,
    KFC_CONCURRENT_A2A_CLOS_GO_SIZE_2 = 21,
    KFC_CONCURRENT_A2A_CLOS_GO_SIZE_3 = 22,
    KFC_CONCURRENT_A2A_CLOS_SLICE_SIZE_PER_JETTY = 23,
    KFC_CONCURRENT_A2A_CLOS_LAST_SLICE_SIZE_PER_JETTY = 24,
    KFC_CONCURRENT_A2A_PARAM_NUM = 25,
};

enum KfcAllToAllMultiJettyParamIndex : uint32_t {
    KFC_A2A_MJ_OP_ID = 0,
    KFC_A2A_MJ_INPUT = 1,
    KFC_A2A_MJ_OUTPUT = 2,
    KFC_A2A_MJ_SLICE_SIZE = 3,
    KFC_A2A_MJ_SRC_STRIDE = 4,
    KFC_A2A_MJ_SRC_OFFSET = 5,
    KFC_A2A_MJ_DST_OFFSET = 6,
    KFC_A2A_MJ_GO_SIZE_0 = 7,
    KFC_A2A_MJ_GO_SIZE_1 = 8,
    KFC_A2A_MJ_GO_SIZE_2 = 9,
    KFC_A2A_MJ_GO_SIZE_3 = 10,
    KFC_A2A_MJ_SLICE_SIZE_PER_JETTY = 11,
    KFC_A2A_MJ_LAST_SLICE_SIZE_PER_JETTY = 12,
    KFC_A2A_MJ_PARAM_NUM = 13,
};

// Sole NHR MultiLink（CcuSchedReduceScatterSoleNHRMultiLink）单帧 xnData 布局：
// [0]=opId 哨兵，NHR 参数从 1 顺排。AIV prepare（CcuPrepareForReduceScatterSoleNhrM2M）写入、
// KFC dispatch 逐槽转发、kernel 形参三处索引必须一致。
enum KfcReduceScatterSoleNhrParamIndex : uint32_t {
    KFC_RS_SOLE_NHR_OP_ID = 0,
    KFC_RS_SOLE_NHR_INPUT = 1,
    KFC_RS_SOLE_NHR_OUTPUT = 2,
    KFC_RS_SOLE_NHR_SLICE_SIZE = 3,
    KFC_RS_SOLE_NHR_INPUT_SLICE_STRIDE = 4,
    KFC_RS_SOLE_NHR_SLICE_ONE_JETTY_SIZE = 5,
    KFC_RS_SOLE_NHR_SLICE_LAST_JETTY_SIZE = 6,
    KFC_RS_SOLE_NHR_REPEAT_NUM_INV = 7,
    KFC_RS_SOLE_NHR_INPUT_REPEAT_STRIDE = 8,
    KFC_RS_SOLE_NHR_OUTPUT_REPEAT_STRIDE = 9,
    KFC_RS_SOLE_NHR_PARAM_NUM = 10,
};

// Sole NHR 2Die（CcuSchedReduceScatterSoleNHR，两级拓扑 L1 NHR 中继）单帧 xnData 布局：
// [0]=opId 哨兵，参数从 1 顺排（token 走 dispatch 的 ctx.token，不占槽；其余 20 参数与 hccl 模板
// taskArgs 布局一致）。双 die 时两个 mission 共享同一区间（参数相同，kernelArg.axisId 区分实例）。
// AIV prepare（CcuPrepareForReduceScatterSoleNhr2DieM2M）写入、KFC dispatch 逐槽转发、
// kernel 形参三处索引必须一致。
enum KfcReduceScatterSoleNhr2DieParamIndex : uint32_t {
    KFC_RS_SOLE_NHR_2DIE_OP_ID = 0,
    KFC_RS_SOLE_NHR_2DIE_INPUT = 1,
    KFC_RS_SOLE_NHR_2DIE_OUTPUT = 2,
    KFC_RS_SOLE_NHR_2DIE_DIE0_SIZE = 3,
    KFC_RS_SOLE_NHR_2DIE_DIE1_SIZE = 4,
    KFC_RS_SOLE_NHR_2DIE_DIE0_LAST_SLICE_SIZE = 5,
    KFC_RS_SOLE_NHR_2DIE_DIE1_LAST_SLICE_SIZE = 6,
    KFC_RS_SOLE_NHR_2DIE_INPUT_SLICE_STRIDE = 7,
    KFC_RS_SOLE_NHR_2DIE_CURRENT_RANK_SLICE_OUTPUT_OFFSET = 8,
    KFC_RS_SOLE_NHR_2DIE_INPUT_REPEAT_STRIDE = 9,
    KFC_RS_SOLE_NHR_2DIE_OUTPUT_REPEAT_STRIDE = 10,
    KFC_RS_SOLE_NHR_2DIE_REPEAT_NUM_VAR = 11,
    KFC_RS_SOLE_NHR_2DIE_IS_INPUT_OUTPUT_EQUAL = 12,
    KFC_RS_SOLE_NHR_2DIE_GO_SIZE_NORMAL_0 = 13,
    KFC_RS_SOLE_NHR_2DIE_GO_SIZE_NORMAL_1 = 14,
    KFC_RS_SOLE_NHR_2DIE_GO_SIZE_NORMAL_2 = 15,
    KFC_RS_SOLE_NHR_2DIE_GO_SIZE_NORMAL_3 = 16,
    KFC_RS_SOLE_NHR_2DIE_GO_SIZE_LAST_0 = 17,
    KFC_RS_SOLE_NHR_2DIE_GO_SIZE_LAST_1 = 18,
    KFC_RS_SOLE_NHR_2DIE_GO_SIZE_LAST_2 = 19,
    KFC_RS_SOLE_NHR_2DIE_GO_SIZE_LAST_3 = 20,
    // die1 专属 goSize 组（双 die 切分后各 die 收尾 GroupCopy 长度不同，按 axisId 选组）
    KFC_RS_SOLE_NHR_2DIE_DIE1_GO_SIZE_NORMAL_0 = 21,
    KFC_RS_SOLE_NHR_2DIE_DIE1_GO_SIZE_NORMAL_1 = 22,
    KFC_RS_SOLE_NHR_2DIE_DIE1_GO_SIZE_NORMAL_2 = 23,
    KFC_RS_SOLE_NHR_2DIE_DIE1_GO_SIZE_NORMAL_3 = 24,
    KFC_RS_SOLE_NHR_2DIE_DIE1_GO_SIZE_LAST_0 = 25,
    KFC_RS_SOLE_NHR_2DIE_DIE1_GO_SIZE_LAST_1 = 26,
    KFC_RS_SOLE_NHR_2DIE_DIE1_GO_SIZE_LAST_2 = 27,
    KFC_RS_SOLE_NHR_2DIE_DIE1_GO_SIZE_LAST_3 = 28,
    KFC_RS_SOLE_NHR_2DIE_PARAM_NUM = 29,
};

// SoleNHR（CcuSchedAllGatherSoleNHR）单帧 xnData 布局：
// [0]=opId 哨兵，参数从 1 顺排。AIV prepare（CcuPrepareForAllGatherSoleNhrM2M）写入、
// KFC dispatch 逐槽转发、kernel 形参三处索引必须一致。
// 单 die 语义：die0Size/die0LastSize 即全量分片与末分片（hccl dieNum=1 口径），die1 参数省略。
enum KfcAllGatherSoleNhrParamIndex : uint32_t {
    KFC_AG_SOLE_NHR_OP_ID = 0,
    KFC_AG_SOLE_NHR_INPUT = 1,
    KFC_AG_SOLE_NHR_OUTPUT = 2,
    KFC_AG_SOLE_NHR_DIE0_SIZE = 3,
    KFC_AG_SOLE_NHR_DIE0_LAST_SIZE = 4,
    KFC_AG_SOLE_NHR_REPEAT_NUM_INV = 5,
    KFC_AG_SOLE_NHR_INPUT_SLICE_STRIDE = 6,
    KFC_AG_SOLE_NHR_OUTPUT_SLICE_STRIDE = 7,
    KFC_AG_SOLE_NHR_INPUT_REPEAT_STRIDE = 8,
    KFC_AG_SOLE_NHR_OUTPUT_REPEAT_STRIDE = 9,
    KFC_AG_SOLE_NHR_INPUT_OUTPUT_EQUAL = 10,
    KFC_AG_SOLE_NHR_GO_SIZE_0 = 11,
    KFC_AG_SOLE_NHR_GO_SIZE_1 = 12,
    KFC_AG_SOLE_NHR_GO_SIZE_2 = 13,
    KFC_AG_SOLE_NHR_GO_SIZE_3 = 14,
    KFC_AG_SOLE_NHR_PARAM_NUM = 15,
};

// ReduceScatter 并发(Mesh+NHR)单帧 xnData 布局：mission0 读 Mesh 区间，mission1 读 NHR 区间。
enum KfcConcurrentReduceScatterParamIndex : uint32_t {
    KFC_CONCURRENT_RS_OP_ID = 0,
    KFC_CONCURRENT_RS_MESH_INPUT = 1,
    KFC_CONCURRENT_RS_MESH_OUTPUT = 2,
    KFC_CONCURRENT_RS_MESH_SCRATCH = 3,
    KFC_CONCURRENT_RS_MESH_RANK_SLICE_OFFSET = 4,
    KFC_CONCURRENT_RS_MESH_CHUNK_SIZE = 5,
    KFC_CONCURRENT_RS_MESH_CHUNK_LOOP_NUM = 6,
    KFC_CONCURRENT_RS_MESH_TAIL_SIZE = 7,
    KFC_CONCURRENT_RS_MESH_FULL_GO_ADDR_OFFSET = 8,
    KFC_CONCURRENT_RS_MESH_FULL_GO_LOOP_PARAM = 9,
    KFC_CONCURRENT_RS_MESH_FULL_GO_PARALLEL_PARAM = 10,
    KFC_CONCURRENT_RS_MESH_FULL_GO_RESIDUAL = 11,
    KFC_CONCURRENT_RS_MESH_TAIL_GO_ADDR_OFFSET = 12,
    KFC_CONCURRENT_RS_MESH_TAIL_GO_LOOP_PARAM = 13,
    KFC_CONCURRENT_RS_MESH_TAIL_GO_PARALLEL_PARAM = 14,
    KFC_CONCURRENT_RS_MESH_TAIL_GO_RESIDUAL = 15,
    KFC_CONCURRENT_RS_MESH_PARAM_NUM = 16,
    KFC_CONCURRENT_RS_NHR_INPUT = KFC_CONCURRENT_RS_MESH_PARAM_NUM,
    KFC_CONCURRENT_RS_NHR_OUTPUT = 17,
    KFC_CONCURRENT_RS_NHR_SLICE_SIZE = 18,
    KFC_CONCURRENT_RS_NHR_INPUT_SLICE_STRIDE = 19,
    KFC_CONCURRENT_RS_NHR_SLICE_ONE_JETTY_SIZE = 20,
    KFC_CONCURRENT_RS_NHR_SLICE_LAST_JETTY_SIZE = 21,
    KFC_CONCURRENT_RS_NHR_REPEAT_NUM_INV = 22,
    KFC_CONCURRENT_RS_NHR_INPUT_REPEAT_STRIDE = 23,
    KFC_CONCURRENT_RS_NHR_OUTPUT_REPEAT_STRIDE = 24,
    KFC_CONCURRENT_RS_PARAM_NUM = 25,
};

} // namespace HcclKfcProtocol

#endif
